FROM golang:1.23.5-alpine3.21 AS builder

WORKDIR /go/src/app

COPY go.mod .
RUN go mod download
COPY main.go .

RUN go build -o /go/bin/server .

FROM scratch

COPY --from=builder /go/bin/server /go/bin/server

CMD ["/go/bin/server"]
